name: egypt_map_chart
description: A Flutter package for displaying Egypt map charts with heat map visualization
version: 0.0.1
homepage: https://github.com/samuel2202-anis/EgyptMapChart
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_maps: 

flutter:
  assets:
    - assets/egypt.json
